## This is to ensure that all codes are automatically checked PRIOR to merging it to main.

name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  eslint-prettier-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm run install

      - name: Sveltekit Check
        run: npm run check

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format
